version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - zip -r BuildArtifact.zip dist/
      - aws s3 cp BuildArtifact.zip s3://mybucketappprueba/backups/build-$(date +%Y%m%d%H%M%S).zip
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: 'dist' # Asumiendo que tu build genera archivos en la carpeta dist