version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Instalando dependencias"
      - npm install
  build:
    commands:
      - echo "Ejecutando build..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
